/**
 * The durable analysis cache as production actually composes it, against a real PostgreSQL server
 * (ADR-0138).
 *
 * This is the test that the pieces are *connected*, which is the whole of what Phase B2 adds and the
 * one thing neither side's own suite can show. The engine's suite proves the orchestrator against
 * fake caches; the persistence suite proves the adapter against a real database. Between them sits
 * the wiring — and ADR-0113's own history is the argument for testing it: every unit test passed
 * while `createPgDependencies` never called `createAnalysisFromEnv`, so the endpoint was dead in
 * production and nothing failed.
 *
 * So the cache here is built by the production factory, `createAnalysisCacheComposition` — the same
 * call `createPgDependencies` makes, with the same pool settings — and it is driven through a real
 * `EngineManager`. Only the engine subprocess is a double, because a UCI binary is the one thing
 * this job cannot install; `FakeEngineTransport` is the engine package's own, and counting its `go`
 * commands is what makes "the engine did not run again" an assertion rather than a hope.
 */
import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import { randomInt } from 'node:crypto';
import type { Pool } from 'pg';
import {
  EngineManager,
  FakeEngineTransport,
  stockfishPlugin,
  type EngineResult,
} from '@chess-platform/engine';
import { migrate, migrationsDir, PgAnalysisCache } from '@chess-platform/persistence/pg';
import { withSharedDatabase } from '@chess-platform/persistence/test-support/fixtures';
import { createAnalysisCacheComposition } from '../src/analysis/durable-cache';
import type { AnalysisCacheComposition } from '../src/analysis/composition';
import { JsonLogger } from '../src/ports/logger';
import { InMemoryMetrics } from '../src/ports/metrics';

const DATABASE_URL = process.env['DATABASE_URL'];
const skip = DATABASE_URL ? false : 'DATABASE_URL not set';

const STOCKFISH_OPTIONS = [
  'option name Threads type spin default 1 min 1 max 512',
  'option name Hash type spin default 16 min 1 max 1024',
  'option name MultiPV type spin default 1 min 1 max 256',
  'option name UCI_Chess960 type check default false',
];

const INFO = 'info depth 10 seldepth 12 nodes 12345 nps 50000 time 200 score cp 20 multipv 1 pv e2e4';

/**
 * The canonical ledger, from the package that owns it — never a schema this file invents.
 *
 * Asked for by that package rather than assembled here from `process.cwd()`, which several suites
 * still do: the working directory is the package root under `npm test` and the repository root
 * under an IDE runner or a hand-written `node --test packages/api/...`, and a suite that can only
 * find its schema from one of those has swapped one hidden precondition for another. A relative
 * path from this file would have the same shape of problem one level down, since it would have to
 * know whether it was running as source or as the emitted `dist-test` copy. `migrationsDir` walks
 * up from the persistence module itself, so it is right in every layout and this file has to know
 * nothing about any of them.
 */
const MIGRATIONS = migrationsDir();

/**
 * Every FEN minted so far and not yet cleaned up, which is this file's claim on the table.
 *
 * A FEN recorded here was generated by this process and appears in no other suite, which is what
 * makes deleting by exact equality an ownership claim: matching the shared `rnbqkbnr/...` placement
 * as a prefix would sweep up every standard starting position in the database, most of which belong
 * to somebody else. The fullmove counters below start at a million to keep that true — the
 * persistence package's own cache suite keys its rows on the canonical `... 0 1`, and this file
 * deletes by FEN without regard to fingerprint, so a counter of 1 minted here would take that row
 * with it.
 *
 * Draining rather than reading assumes these tests run one at a time, which is what
 * `--test-concurrency=1` and node's sequential top-level tests give: a test that opted itself into
 * concurrency would have its rows deleted by a neighbour's cleanup. The sibling suite for this same
 * table makes the same assumption, at `packages/persistence/test/analysis-cache.integration.test.ts`.
 */
const mintedFens: string[] = [];

/** The same FENs, kept for the whole file rather than drained, so `after` can audit the cleanup. */
const allFens: string[] = [];

/**
 * A position unique to this run, recorded before it can be used.
 *
 * The cache identity includes the FEN, and these suites share a database with every other
 * integration file and with previous runs of themselves. Varying the fullmove counter keeps the FEN
 * structurally valid while making each test's identity its own, so a leftover row can neither
 * satisfy a request this test meant to miss nor be mistaken for one it wrote.
 *
 * Uniqueness was mistaken for cleanup, and it is not: minting a fresh identity means the *next* run
 * never collides, not that this one took its rows back. It left five rows in `engine_analysis_cache`
 * every time it ran. Recording happens here, before the caller can analyse anything, so a body that
 * throws between minting the FEN and writing the row still hands cleanup an identity it owns.
 */
function freshFen(): string {
  const fen = `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 ${randomInt(1_000_000, 2_000_000)}`;
  mintedFens.push(fen);
  allFens.push(fen);
  return fen;
}

/**
 * Say out loud that the file left nothing behind.
 *
 * Cleanup that quietly stopped deleting would go on passing indefinitely otherwise: every identity
 * is minted fresh, so residue never collides with anything a later run asks for. The ownership
 * regression beside this file makes the same reading from outside, and more strictly — it can also
 * see rows *wrongly* removed. This one is here because it is the reading a developer running only
 * this file still gets.
 */
after(async () => {
  if (!DATABASE_URL || allFens.length === 0) return;
  await withSharedDatabase({ max: 2, cleanup: async () => undefined }, async (pool) => {
    const left = await pool.query<{ n: string }>(
      'SELECT count(*)::text AS n FROM engine_analysis_cache WHERE fen = ANY($1::text[])',
      [allFens],
    );
    assert.equal(left.rows[0]?.n, '0', 'every row this file wrote was removed again');
  });
});

/**
 * Apply the ledger the first time only; later calls on later pools are no-ops.
 *
 * The suite needs `engine_analysis_cache` (0026) and its `updated_at` index (0027), and used to
 * assume some earlier package had built them: the persistence suites migrate `DATABASE_URL` and run
 * before this one in both the root `test` script and the `postgres-integration` CI job. Run against
 * a database nobody had prepared, six of these ten tests failed — three throwing SQLSTATE 42P01 and
 * three quietly asserting on a durable row that was never written, because the cache absorbs a
 * missing table as a fault and degrades to computing.
 *
 * A flag rather than a memoized promise: a promise would stay bound to the first test's pool, which
 * `withDatabase` closes on the way out, so a later caller awaiting it for its own connection would
 * be waiting on a pool that no longer exists.
 */
let migrated = false;

async function ensureMigrated(pool: Pool): Promise<void> {
  if (migrated) return;
  await migrate(pool, MIGRATIONS);
  migrated = true;
}

/**
 * Run one test against the shared database, then take back the rows it wrote.
 *
 * `withSharedDatabase` rather than a `try/finally` around the `DELETE`: a `finally` that awaits
 * cleanup lets a failing `DELETE` replace the assertion that actually failed, and cleanup here runs
 * on the path where it matters most — a failing test is the one someone reruns. It says nothing
 * about the `finally` blocks inside the bodies below, which shut engines down: a `shutdown()` that
 * rejects while an assertion is already failing still replaces it, as it did before this change.
 */
async function withDatabase(body: (pool: Pool) => Promise<void>): Promise<void> {
  // Two connections for *this* pool — enough for `migrate`, which holds its advisory lock on a
  // dedicated client while running its statements on another. It is not a budget for the file: each
  // `instance()` builds the production cache pool, which is four more.
  await withSharedDatabase({ max: 2, cleanup: deleteMintedRows }, async (pool) => {
    await ensureMigrated(pool);
    await body(pool);
  });
}

/**
 * Remove every row keyed by a FEN minted so far, then forget them.
 *
 * The list is drained rather than read, so a test that failed partway hands the next one an empty
 * ledger instead of re-deleting rows that are already gone. Deleting by FEN alone rather than by the
 * whole composite key is deliberate: one FEN can carry rows under several engine fingerprints — the
 * upgrade case is a whole test here — and this file minted every one of them.
 */
async function deleteMintedRows(pool: Pool): Promise<void> {
  const fens = mintedFens.splice(0, mintedFens.length);
  if (fens.length === 0) return;
  await pool.query('DELETE FROM engine_analysis_cache WHERE fen = ANY($1::text[])', [fens]);
}

interface Instance {
  readonly manager: EngineManager;
  readonly tier: AnalysisCacheComposition;
  readonly metrics: InMemoryMetrics;
  /** How many times a worker was actually asked to search. */
  searches(): number;
  shutdown(): Promise<void>;
}

/**
 * One process's worth of the production composition: a cache tier from the real factory, and an
 * `EngineManager` wired to it exactly as `createAnalysisEngine` wires one.
 */
function instance(options: { engineName?: string; connectionString?: string } = {}): Instance {
  const metrics = new InMemoryMetrics();
  const logger = new JsonLogger({}, { level: 'error', sink: () => {} });
  const tier = createAnalysisCacheComposition({
    settings: { durable: true, ttlMs: 30 * 86_400_000, hotEntries: 500 },
    logger,
    metrics,
    connectionString: options.connectionString ?? DATABASE_URL,
  });

  let searches = 0;
  const manager = new EngineManager({
    transportFactory: () =>
      new FakeEngineTransport({
        name: options.engineName ?? 'Stockfish 16',
        optionLines: STOCKFISH_OPTIONS,
        go: () => {
          searches += 1;
          return { info: [INFO], bestmove: 'e2e4' };
        },
      }),
    ...(tier.cache !== undefined ? { cache: tier.cache } : {}),
    observer: tier.observer,
    minWorkers: 0,
    maxWorkers: 1,
  });
  manager.register(stockfishPlugin);

  return {
    manager,
    tier,
    metrics,
    searches: () => searches,
    shutdown: async () => {
      // The same order the composition uses: drain the engine, then release the cache, so a search
      // finishing during shutdown can still store what it found.
      await manager.shutdown({ deadlineMs: 2_000 });
      await tier.shutdown();
    },
  };
}

/** One analysis request, with the limits every test here shares so results stay comparable. */
async function analyze(node: Instance, fen: string): Promise<readonly EngineResult[]> {
  return node.manager.analyze({ fen, variant: 'standard', limits: { depth: 10 } });
}

/**
 * Read one counter out of the rendered Prometheus text.
 *
 * Rendering rather than reaching into the registry keeps these assertions honest about what an
 * operator would actually scrape, including the label set.
 */
function counter(metrics: InMemoryMetrics, series: string): number {
  const match = new RegExp(`^${series} (\\d+(?:\\.\\d+)?)$`, 'm').exec(metrics.render());
  return match ? Number(match[1]) : 0;
}

test('a cold position is computed once and then served from the database', { skip }, async () => {
  await withDatabase(async () => {
    const node = instance();
    const fen = freshFen();
    try {
      const first = await analyze(node, fen);
      assert.equal(node.searches(), 1, 'a cold identity must reach the engine');

      const second = await analyze(node, fen);
      assert.deepEqual(second, first, 'the cached analysis is the analysis, not an approximation');
      assert.equal(node.searches(), 1, 'the second request must not run a search');

      assert.equal(counter(node.metrics, 'analysis_cache_events_total{event="cache_hit"}'), 1);
      assert.equal(counter(node.metrics, 'analysis_cache_events_total{event="cache_miss"}'), 1);
      assert.equal(counter(node.metrics, 'analysis_cache_faults_total{fault="read"}'), 0);
    } finally {
      await node.shutdown();
    }
  });
});

/**
 * The reason the cache is durable at all.
 *
 * An in-process cache cannot do this: its entries die with the process that made them, so every
 * replica starts cold and every deploy throws the fleet's accumulated analysis away. Instance B here
 * has its own pool, its own manager and its own workers, and shares nothing with A but the table.
 */
test('a second instance reuses what the first stored, with no engine of its own', { skip }, async () => {
  await withDatabase(async () => {
    const fen = freshFen();
    const first = instance();
    try {
      await analyze(first, fen);
      assert.equal(first.searches(), 1);
    } finally {
      await first.shutdown();
    }

    const second = instance();
    try {
      const results = await analyze(second, fen);
      assert.equal(second.searches(), 0, 'the durable row must answer without a search');
      assert.equal(results[0]?.depth, 10, 'and must carry the analysis the first instance found');
      assert.equal(counter(second.metrics, 'analysis_cache_events_total{event="cache_hit"}'), 1);
    } finally {
      await second.shutdown();
    }
  });
});

/**
 * Identity survives the composition, which was ADR-0135 §7's first precondition for wiring this up.
 * A different engine build advertises different options, which changes its fingerprint, which is a
 * different row — so an upgrade cannot serve yesterday's analysis as today's.
 */
test('a different engine build does not read the first build\'s rows', { skip }, async () => {
  await withDatabase(async () => {
    const fen = freshFen();
    const sixteen = instance({ engineName: 'Stockfish 16' });
    try {
      await analyze(sixteen, fen);
      assert.equal(sixteen.searches(), 1);
    } finally {
      await sixteen.shutdown();
    }

    const seventeen = instance({ engineName: 'Stockfish 17' });
    try {
      await analyze(seventeen, fen);
      assert.equal(seventeen.searches(), 1, 'a new build must compute rather than inherit');
      assert.equal(counter(seventeen.metrics, 'analysis_cache_events_total{event="cache_hit"}'), 0);
    } finally {
      await seventeen.shutdown();
    }
  });
});

/**
 * The failure ADR-0135 §6 promised: a database outage costs recomputation, never an error, and never
 * silence.
 *
 * The last assertion is the subtle one and the reason the fault counter exists at all. A failed
 * write still resolves, so the engine records `cache_write_completed` — an operator watching engine
 * events alone would see a perfectly healthy cache throughout a total outage. Only the fault counter
 * can tell those apart.
 */
test('a dead database costs a recomputation, not a failed analysis', { skip }, async () => {
  await withDatabase(async () => {
    const node = instance();
    const fen = freshFen();
    try {
      // Kill the cache underneath a live manager: every subsequent get and set fails.
      await node.tier.shutdown();

      const results = await analyze(node, fen);

      assert.equal(results.length, 1, 'the caller still gets a real analysis');
      assert.equal(results[0]?.evaluation.value, 20);
      assert.equal(node.searches(), 1, 'exactly one search, from the one request');
      assert.equal(counter(node.metrics, 'analysis_cache_faults_total{fault="read"}'), 1);
      assert.equal(counter(node.metrics, 'analysis_cache_faults_total{fault="write"}'), 1);
      assert.equal(
        counter(node.metrics, 'analysis_cache_events_total{event="cache_write_completed"}'),
        1,
        'the engine cannot see that the write failed — which is precisely why the fault counter exists',
      );
    } finally {
      await node.manager.shutdown({ deadlineMs: 2_000 });
    }
  });
});

test('a storm of identical requests against a dead cache still runs one search', { skip }, async () => {
  await withDatabase(async () => {
    const node = instance();
    const fen = freshFen();
    try {
      await node.tier.shutdown();

      const results = await Promise.all(Array.from({ length: 8 }, () => analyze(node, fen)));

      // Single-flight is process-local and unaffected by the cache being gone: eight callers that
      // ask for the same identity join one flight, so a cache outage cannot turn request volume
      // into engine volume.
      assert.equal(node.searches(), 1, 'eight callers, one search');
      assert.equal(counter(node.metrics, 'analysis_cache_events_total{event="request_coalesced"}'), 7);
      for (const result of results) assert.equal(result[0]?.depth, 10);
    } finally {
      await node.manager.shutdown({ deadlineMs: 2_000 });
    }
  });
});

/**
 * What the durable cache does *not* provide, asserted so the claim in the docs is checked rather
 * than merely written down.
 *
 * Single-flight is a map inside one `AnalysisOrchestrator`. Two processes racing on the same cold
 * position therefore both compute it: nothing in PostgreSQL coordinates them, because nothing was
 * asked to. Both results are correct and the stronger survives the upsert; the cost is one duplicated
 * search on a cold miss, which is the price of not adding a distributed lock.
 */
test('two live instances racing a cold position both compute it', { skip }, async () => {
  await withDatabase(async () => {
    const fen = freshFen();
    const a = instance();
    const b = instance();
    try {
      await Promise.all([analyze(a, fen), analyze(b, fen)]);

      assert.equal(a.searches() + b.searches(), 2, 'cross-process single-flight does not exist');

      // And the race resolves to one row that either of them can then read.
      const reader = instance();
      try {
        await analyze(reader, fen);
        assert.equal(reader.searches(), 0, 'the duplicated work still leaves one usable row');
      } finally {
        await reader.shutdown();
      }
    } finally {
      // Nested rather than sequential: a rejection from the first `shutdown` would otherwise skip
      // the second, leaving the other instance's pool and engine worker behind.
      try {
        await a.shutdown();
      } finally {
        await b.shutdown();
      }
    }
  });
});

test('a cache pool that cannot connect degrades to computing, and says so', { skip }, async () => {
  // Wrapped like the rest even though its cache never reaches a database: the FEN it mints is
  // registered the moment it is minted, so it belongs to a cleanup somewhere, and a `DELETE` that
  // matches nothing is the correct outcome rather than a special case.
  await withDatabase(async () => {
    // Port 1 is not a PostgreSQL server, so every statement fails at connection time — the shape of
    // a misconfigured or unreachable database, as opposed to one that was closed.
    const node = instance({ connectionString: 'postgres://nobody:nobody@127.0.0.1:1/none' });
    try {
      const results = await analyze(node, freshFen());

      assert.equal(results.length, 1, 'analysis is unaffected by a cache it cannot reach');
      assert.equal(node.searches(), 1);
      assert.ok(
        counter(node.metrics, 'analysis_cache_faults_total{fault="read"}') >= 1,
        'an unreachable cache must be reported, not merely missed',
      );
    } finally {
      await node.shutdown();
    }
  });
});

/**
 * The pool the production factory built really is bounded — asserted through the tier, not beside it.
 *
 * The unit test asserts the config object; this asserts that the object reaches the pool. An
 * exclusive table lock makes the lookup hang for real, so without `statement_timeout` on this pool
 * the analysis would wait for the lock rather than the bound, and this test would stop finishing.
 */
test('a lookup that would hang is bounded by the pool the factory built', { skip }, async () => {
  await withDatabase(async (pool) => {
    const node = instance();
    // The engine is shut down however this exits, acquisition included: a pool that could not hand
    // out a connection would otherwise leave the composition's own pool and retention timer behind,
    // and an open handle is how a failing test becomes a hanging one.
    try {
      // The lock is held on a connection from this test's own pool rather than a third one built
      // for the purpose: the cache under test has a pool of its own, so these are already different
      // backends, which is all the lock needs to bite.
      const holder = await pool.connect();
      try {
        await holder.query('BEGIN');
        await holder.query('LOCK TABLE engine_analysis_cache IN ACCESS EXCLUSIVE MODE');

        const startedAt = Date.now();
        const results = await analyze(node, freshFen());
        const elapsed = Date.now() - startedAt;

        assert.equal(results.length, 1, 'the analysis still completes');
        assert.equal(node.searches(), 1);
        assert.ok(elapsed < 10_000, `the cache must not wait on the lock (took ${elapsed}ms)`);
        assert.ok(
          counter(node.metrics, 'analysis_cache_faults_total{fault="read"}') >= 1,
          'the bounded read is reported as a fault, not passed off as a cold cache',
        );
      } finally {
        // Released before cleanup runs, and rolled back first: a connection handed back mid
        // transaction would still hold the exclusive lock, and the `DELETE` that follows would wait
        // on it forever.
        await holder.query('ROLLBACK').catch(() => {});
        holder.release();
      }
    } finally {
      await node.shutdown();
    }
  });
});

/**
 * The one thing the hot tier changes about durable behaviour, asserted rather than merely documented
 * (ADR-0139 §3 and Consequences).
 *
 * A process that has cached a position answers from memory for up to `HOT_CACHE_TTL_MS` after the
 * row behind it is gone. That is the whole of the staleness this tier can introduce: it is bounded,
 * it does not grow with traffic, and it does not reach any other replica. Deleting the row outright
 * is the strongest available form of "the durable tier no longer has this" — stronger than letting
 * retention expire it — so if the bound ever stopped holding, this is where it would show.
 */
test('a hot entry outlives the row it came from, by a bounded amount', { skip }, async () => {
  await withDatabase(async (pool) => {
    const node = instance();
    const fen = freshFen();
    try {
      await analyze(node, fen);
      assert.equal(node.searches(), 1);

      // Asserted, because a zero-row delete would make the rest of this test vacuous: if the
      // durable write had never landed, the hot tier would answer for the ordinary reason and the
      // fresh instance would recompute for the ordinary reason, and nothing about staleness would
      // have been shown. Raised in the CodeRabbit review of PR #19.
      const removed = await pool.query('DELETE FROM engine_analysis_cache WHERE fen = $1', [fen]);
      assert.equal(removed.rowCount, 1, 'the durable row must have existed for its loss to mean anything');

      await analyze(node, fen);
      assert.equal(node.searches(), 1, 'memory answers without consulting the table it no longer needs');

      // A process that never cached it sees the truth at once, so the staleness is this one
      // process's memory and nothing wider — no other replica can inherit it.
      const cold = instance();
      try {
        await analyze(cold, fen);
        assert.equal(cold.searches(), 1, 'the row really is gone everywhere else');
      } finally {
        await cold.shutdown();
      }
    } finally {
      // The row `cold` wrote back is not deleted here: it is keyed by a FEN this file minted, so
      // the cleanup `withDatabase` runs takes it, on the failure path as well as this one.
      await node.shutdown();
    }
  });
});

test('the retention sweep runs against the composed cache without disturbing it', { skip }, async () => {
  await withDatabase(async (pool) => {
    const node = instance();
    const fen = freshFen();
    try {
      await analyze(node, fen);
      assert.equal(node.searches(), 1);

      // File the row in the last century and sweep with a cutoff at the millennium. The sweep is
      // deliberately table-wide, so a cutoff of "a day ago" would also match anything an earlier
      // run left behind and the exact count below would be a property of the database rather than
      // of the sweep. Nothing else ever writes a row this old.
      await pool.query(
        `UPDATE engine_analysis_cache SET updated_at = TIMESTAMPTZ '1999-01-01' WHERE fen = $1`,
        [fen],
      );
      // Swept through the adapter, which is exactly what `AnalysisCacheRetention` holds in
      // production: the durable half of the tier, not the hot cache in front of it (ADR-0139 §2).
      // `deleteExpired` is the adapter's own and never was part of the `AnalysisCache` port.
      // At least one, not exactly one. Nothing else *writes* a row this old, but a previous run
      // that died between the back-dating above and its cleanup below would leave one, and then an
      // exact count would be a property of the database rather than of the sweep. That this row in
      // particular went is proven below, by a process that has to reach the table to find out.
      const durable = new PgAnalysisCache(pool);
      assert.ok((await durable.deleteExpired(new Date('2000-01-01T00:00:00Z'), 100)) >= 1);

      // The identity is gone from the table, so a process that never cached it recomputes — an
      // expired entry costs one search, and the cache heals itself. It is asked on a *fresh*
      // instance because `node` still holds the position in its own hot tier; that entry outliving
      // the row it came from is ADR-0139's bounded staleness, pinned by the test above.
      const cold = instance();
      try {
        await analyze(cold, fen);
        assert.equal(cold.searches(), 1, 'an expired row must not still answer');
      } finally {
        await cold.shutdown();
      }

      // And the recomputation really did land in the table, rather than only in the process that
      // made it — which a second lookup on `cold` could not have shown, because its own hot tier
      // would have answered before PostgreSQL was ever asked.
      const reader = instance();
      try {
        await analyze(reader, fen);
        assert.equal(reader.searches(), 0, 'the recomputed row must be durable, not merely in memory');
      } finally {
        await reader.shutdown();
      }
    } finally {
      await node.shutdown();
    }
  });
});
